import './globals.css';
import React from 'react';
import Header from '../Header/header';
import Footer from "@/Header/footer";
import Head from 'next/head';  // Import Head component

export const metadata = {
    title: 'Flix',
    description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <Head>
            <title>Flix</title>

            <link rel="icon" href="/tree.png" />
        </Head>
        <body>
        <Header />
        <main>{children}</main>
        <Footer />
        </body>
        </html>
    );
}
